# Generated by Django 2.2.1 on 2019-05-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='level',
        ),
        migrations.AddField(
            model_name='metric',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
