# Generated by Django 2.2.1 on 2019-05-30 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0002_auto_20190530_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='level',
            field=models.IntegerField(default=0, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='metric_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widget.Agent', verbose_name='Metrica'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='value',
            field=models.CharField(max_length=100, verbose_name='Valor'),
        ),
    ]
