# Generated by Django 2.2.1 on 2019-05-30 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0005_remove_metric_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metric',
            old_name='metric_id',
            new_name='metric',
        ),
    ]
