# Generated by Django 2.2.1 on 2019-06-06 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0010_auto_20190606_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='widget',
            options={'verbose_name': 'Widget', 'verbose_name_plural': 'Widgets'},
        ),
        migrations.RemoveField(
            model_name='widget',
            name='id',
        ),
        migrations.AlterField(
            model_name='widget',
            name='agent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='widget.Agent', verbose_name='Agent'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='label',
            field=models.CharField(default='', max_length=50, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='total_level',
            field=models.IntegerField(choices=[(3, 'Tres'), (5, 'Cinco'), (6, 'Seis')], default=3, verbose_name='Total'),
        ),
    ]
