# Generated by Django 2.2.1 on 2019-05-30 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0004_auto_20190530_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='is_active',
        ),
    ]
