# Generated by Django 2.2.1 on 2019-05-31 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0006_auto_20190530_0734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metric',
            old_name='metric',
            new_name='agent',
        ),
    ]
