# Generated by Django 2.2.1 on 2019-06-06 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0007_auto_20190530_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='level',
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='Label')),
                ('level', models.IntegerField(default=0, verbose_name='Nivel')),
                ('total_level', models.IntegerField(default=0, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widget.Agent', verbose_name='Metrica')),
            ],
        ),
    ]
